#!/bin/sh

set -e
set -x

if [ -z $ANDROID_HOME ]; then
    if [ -e ~/.android/bashrc ]; then
        . ~/.android/bashrc
    else
        echo "ANDROID_HOME must be set!"
        exit
    fi
fi

git submodule sync --recursive
git submodule foreach --recursive "git submodule sync"
git submodule update --init --recursive

make -C external/ clean
make -C external/ assets
./update-ant-build.sh
