#!/system/bin/sh 

export TERM=linux
export HOSTNAME=debian
export HOME=/root
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/system/xbin:/system/bin

chroot /data/debian /bin/bash --login -i
