#!/bin/sh
# this is the common settings for the various scripts here

export TERM=linux
export HOME=/root
export HOSTNAME=debian
export PATH=/usr/sbin:/usr/bin:/sbin:/bin:/sbin:/system/sbin:/system/bin:/system/xbin:/data/local/bin

if [ $# -lt 1 ]; then
    echo "incorrect number of arguments, should be between 1 and 7:"
    echo "    $0 dataDir [sdcard] [imagefile] [mnt] [release] [mirror] [imagesize]"
fi

dataDir=$1
if [ -z $sdcard ]; then
    sdcard=$2
fi
if [ -z $imagefile ]; then
    imagefile=$3
fi
if [ -z $mnt ]; then
    mnt=$4
fi
if [ -z $release ]; then
    release=$5
fi    
if [ -z $mirror ]; then
    mirror=$6
fi    
if [ -z $imagesize ]; then
    imagesize=$7
fi    

test -d $dataDir || echo "dataDir: '$dataDir' not a directory"
test -d $sdcard || echo "sdcard: '$sdcard' not a directory"
test -z $imagefile && echo "imagefile: '$imagefile' is empty"
test -z $mnt && echo "mnt: '$mnt' is empty"

loopdev=/dev/block/loop4
busybox_path=/data/busybox
busybox=$busybox_path/busybox

make_root_symlinks () {
    wd=`pwd`
    cd /
    mount -oremount,rw rootfs /
    for x in \
        bin boot home media opt selinux srv usr var tmp
    do
        ln -s $mnt/$x /$x
    done
    mount -oremount,ro rootfs /
    cd "$wd"
}

remove_root_symlinks () {
    cd /
    mount -oremount,rw rootfs /
    for x in \
        bin boot home media opt selinux srv usr var tmp
    do
        rm /$x
    done
    mount -oremount,ro rootfs /
}
