#!/system/bin/sh 

export TERM=linux
export HOSTNAME=debian
export HOME=/root
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/system/xbin:/system/bin
app_bin=/data/data/info.guardianproject.lildebi/app_bin

username=`$app_bin/whoami`
id=`$app_bin/id -u`
if [ "$id" -eq 0 ]; then
# try using the chroot included in LilDebi, otherwise fail over to a possible system one
    PATH=$app_bin $app_bin/chroot /debian /bin/bash --login -i \
        || chroot /debian /bin/bash --login -i
elif grep "^${username}:" /debian/etc/passwd > /dev/null; then
    su -c "PATH=$app_bin $app_bin/chroot /debian /bin/su $username --login"
else
    su -c "PATH=$app_bin $app_bin/chroot /debian /bin/bash --login -i"
fi
